version: "3.9"

services:

  backend:

    build:
      context: .
      dockerfile: Dockerfile

    container_name: smart-retail-backend

    restart: unless-stopped

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/app

    command: >
      uvicorn src.main:app
      --host 0.0.0.0
      --port 8000

    networks:
      - smart-retail-network

  frontend:

    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: smart-retail-frontend

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "4173:4173"

    command: >
      npm run preview

    environment:
      VITE_API_URL: http://127.0.0.1:8000/api/v1/detect

    networks:
      - smart-retail-network

networks:

  smart-retail-network:

    driver: bridge
